theme: jekyll-theme-minimal
title: KYLE LEE
logo: <img src="https://github.com/kylelee2062/Kyle_Lee_Portfolio/blob/main/images/unnamed.jpg" width="562.5" height="750">
show_downloads: true
google_analytics:
